//EDIT SETTINGS TEST
module.exports = (browser, data) => {
    browser
        .moveToElement('@profileNavLink', 32, 54)
        .click('@settingsButton')
        .click('@editGender')
        .click('@editLocation')
        .click('@editPrimaryClub')
        .click('@editWeight')
        .click('@editVanityUrl')
        .pause(500)
        .click('@editBio')
        .click('@genderRadioButton')
        .clearValue('@enterLocation')
        .setValue('@enterLocation', 'Beaumont,TX')
        .click('@selectPrimaryClub')
        .click('@selectSETXVELO')
        .clearValue('@enterWeight')
        .setValue('@enterWeight', '140')
        .setValue('@enterVanityUrl', 'davisdbrianna')
        .setValue('@enterBio', 'I enjoy cycling, skating, hiking, and taking an occasional jog to the mailbox.')
        .click('@genderSaveButton')
        .pause(500)
        .click('@locationSaveButton')
        .pause(500)
        .click('@primaryClubSaveButton')
        .pause(500)
        .click('@weightSaveButton')
        .pause(500)
        .click('@vanityUrlSaveButton')
        .pause(500)
        .click('@bioSaveButton')
        .pause(5000)
}